### ISSUE TITLE
期待此插件能支持node ~0.12版本

### ISSUE THREAD

**Issue by asoiso** [fex-team/fis-spriter-csssprites#10]
现在此插件不支持0.12.1、0.12.2，node小版本升级基本上是修改bug、优化，不会做大的变化，期待此插件能支持node ~0.12版本

**Comment by xiangshouding** [comment]
没问题啊，node 0.12.1，0.12.2都是支持的呀。

**Comment by asoiso** [comment]
[WARNI] csssprites does not support your node v0.12.2, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues

**Comment by xiangshouding** [comment]
@asoiso Linux 32 没有编译图片库以外都其他都提供了，难道还是不行？你什么系统

**Comment by asoiso** [comment]
已解决，刚刚更新了一下fis

**Comment by asoiso** [comment]
[WARNI] node-pngcrush does not support your node v0.12.2, report it to https://github.com/xiangshouding/node-pngcrush/issues

我觉得这个提示应该再修改一下，提示用户去更新node或者fis

**Comment by xiangshouding** [comment]
@asoiso 🐵
