### ISSUE TITLE
能否自动获取到需要sprite图片的宽高并直接插入到样式中

### ISSUE THREAD

**Issue by DeyuanTan** [fex-team/fis-spriter-csssprites#13]
![image](https://cloud.githubusercontent.com/assets/8966624/7559781/69ff1fa0-f7ee-11e4-9ef2-0a5b1f5c3d83.png)

如图所示，背景图片一般都需要指定宽高。如果不指定宽高有时背景图片无法显示。如图中所示的宽高能直接读取背景图片的宽高就好了

**Comment by fouber** [comment]
@DeyuanTan 

引入less/sass等预编译处理应该就可以了

**Comment by fouber** [comment]
@DeyuanTan 
不过获取sprite图片的宽高应该没意义吧，等到图片合并之后，真正使用的图片大小就发生了变化，这个宽高拿来做什么呢？

**Comment by DeyuanTan** [comment]
如果没有设置div宽高，背景显示不出来~

**Comment by DeyuanTan** [comment]
![image](https://cloud.githubusercontent.com/assets/8966624/7559957/a644f4ba-f7f0-11e4-84a3-609df17b0998.png)  
比如这个图片本来是 29*69px，没有指定宽高，使用的时候只显示其中一部分
![image](https://cloud.githubusercontent.com/assets/8966624/7559980/da7f159e-f7f0-11e4-89b3-9d7c3400813e.png)

**Comment by fouber** [comment]
这个于sprite有关么？即使不做sprite，如果不设置宽高也是看不完整的啊，这只是业务的问题而已

**Comment by DeyuanTan** [comment]
@fouber 没错，不论是否做sprite，宽高都是要写的。如果读取到图片的宽高并加入到css中，写样式时就不需要关心DIV宽高问题。提高效率。

**Comment by fouber** [comment]
@DeyuanTan 

less/sass/stylus中某个预编译处理过程是有获取图片宽高功能的

**Comment by fouber** [comment]
@DeyuanTan 

比如stylus中的image-size，我们使用stylus配合fis生成sprite的时候是这样写的：

```stylus
sprite($url)
    background: url($url + '?__sprite') no-repeat;
    background-size: (image-size($url)[0] / 2) (image-size($url)[1] / 2);
```

这样，任何需要sprite的地方，我们的代码就写成：

```stylus
.foo {
    sprite('foo.png');
}
```
就行了

**Comment by xiangshouding** [comment]
这个赞；

**Comment by DeyuanTan** [comment]
@xiangshouding  fisp 内置 fis-spriter-csssprites 用的less是1.7，无法使用内置函数获取到图像宽高，能否升级至2.2？

![image](https://cloud.githubusercontent.com/assets/8966624/7561828/b3b2d598-f801-11e4-9d4a-0888c808cc1d.png)

**Comment by DeyuanTan** [comment]
![image](https://cloud.githubusercontent.com/assets/8966624/7561947/d99a4c0e-f802-11e4-872f-deb9ad3e18ed.png)

**Comment by DeyuanTan** [comment]
@xiangshouding 预计什么时候升级 fis-parser-less  LESS版本至2.2+？
