### ISSUE TITLE
能否支持打出多张图片

### ISSUE THREAD

**Issue by yanhaijing** [fex-team/fis-spriter-csssprites#14]
这个需求的场景是这样，对于移动端的页面，应用图片比较多时，我不希望都打成一张图片，会影像首屏的渲染，希望把首屏图片打成一张，其他图片打成一张，希望加一个参数可以用来控制那些图片打成同一张图片例如

```
?__sprite_1
?__sprite_2
?__sprite_3
```

**Comment by mudoo** [comment]
https://github.com/mudoo/fis-spriter-csssprites-group

**Comment by yanhaijing** [comment]
@mudoo 好赞
