### ISSUE TITLE
csssprites does not support your node v0.12.4

### ISSUE THREAD

**Issue by gunsnakee** [fex-team/fis-spriter-csssprites#17]
csssprites does not support your node v0.12.4

**Comment by xiangshouding** [comment]
请安装最新版本 fisp 或者 fis，如再出现类似报错，请提供你的机器信息，包括操作系统，32 / 64 位，如果是 Linux 系统，请一并提供 glibc 版本

**Comment by gunsnakee** [comment]
升级到最新版本的fis，果然可以了
