### ISSUE TITLE
不支持v0.12.4版本的node

### ISSUE THREAD

**Issue by cpd0101** [fex-team/fis-spriter-csssprites#18]
csssprites does not support your node v0.12.4, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues
情况为2015-6-3号领到的新Mac，fis与node都是最新的。

**Comment by xiangshouding** [comment]
那就降级 node 吧

**Comment by jincdream** [comment]
https://github.com/zhangyuanwei/node-images/issues/46 只能等

**Comment by cpd0101** [comment]
已降级处理
