### ISSUE TITLE
less支持吗？

### ISSUE THREAD

**Issue by annnhan** [fex-team/fis-spriter-csssprites#21]
RT

**Comment by xiangshouding** [comment]
支持

**Comment by anjorweb** [comment]
我就是这么处理的，然而csssprite无效呀。

`fis.match('*.less', {
  parser: fis.plugin('less'),
  rExt: '.css'
});
// 启用 fis-spriter-csssprites 插件
fis.match('::package', {
  spriter: fis.plugin('csssprites')
})
fis.match('*.css', {
  optimizer: fis.plugin('clean-css'),
  useSprite: true
});`
