### ISSUE TITLE
奇怪了 node v0.12.7不支持使用

### ISSUE THREAD

**Issue by vincentyung** [fex-team/fis-spriter-csssprites#23]
[WARNI] csssprites does not support your node v0.12.7, report it to https://git
hub.com/xiangshouding/fis-spriter-csssprites/issues

fis 为v1.9.31

**Comment by xiangshouding** [comment]
什么系统，32 还是 64 的

**Comment by front-end-syb** [comment]
我这里也不行哦，64位，一直回滚到0.8.0才能用。

**Comment by vincentyung** [comment]
win8 64位

**Comment by xiangshouding** [comment]
确定是装的 64 位的 node 吗？

**Comment by vincentyung** [comment]
node-v0.10.28-x64.msi

**Comment by vincentyung** [comment]
node-v0.12.7-x64.msi 装的是这个

**Comment by chilebaby** [comment]
我这里也是这个问题

**Comment by xiangshouding** [comment]
我找个测试环境试试。

**Comment by xiangshouding** [comment]
各位，没复现。我用的系统 Windows 7 64位，node v0.12.7 64 位，fis-spriter-csssprites 用的最新版本。

**Comment by xiangshouding** [comment]
8.x 已支持
