### ISSUE TITLE
和 hook-relative 同时使用的时候合并出错

### ISSUE THREAD

**Issue by tcdona** [fex-team/fis-spriter-csssprites#25]
有同学暂时修复了

https://github.com/allanfish/fis-spriter-csssprites/blob/master/libs/cssParser.js#L18

还是希望官方看看咋办比较好

**Comment by tcdona** [comment]
之所以出现这个bug，应该是插件里面获取文件uri的方式没有统一，上面同学单独处理的方式肯定不会适用所有情况的，还需考虑成熟点！

**Comment by kaiye** [comment]
两个插件确实无法同时使用 +1

**Comment by allanfish** [comment]
[atm3-spriter-csssprites](https://github.com/femxd/atm3-spriter-csssprites)这个插件增强了雪碧图功能, 支持如下特性: 
- 指定雪碧图发布路径
- 一个css中的图片可以合并到多张雪碧图中, 方便性能优化

**Comment by jincdream** [comment]
@allanfish 有支持node v5 吗？

**Comment by jincdream** [comment]
@allanfish 有支持node v5 吗？
