### ISSUE TITLE
 [WARNI] csssprites does not support your node v4.0.0,

### ISSUE THREAD

**Issue by PeakFish** [fex-team/fis-spriter-csssprites#27]
win7 64位 
fis3 v3.2.0 
fis-spriter-csssprites version 0.3.0

**Comment by xiangshouding** [comment]
二进制插件没办法这么快速的适配最新的 node，计划下周内适配完成。

**Comment by DeyuanTan** [comment]
这个问题还没搞好？

**Comment by xiangshouding** [comment]
是的，正在进行中，接口变动比较大，而我们研发的二进制插件又比较多，希望有点耐心。

可以暂时切到低版本 node 继续使用；

**Comment by kidming** [comment]
我还以为node版本低呢，所以嗨升了一次级呢，结果原来是版本高了啊

**Comment by Hancoson** [comment]
这个问题什么时候可以解决呢？

**Comment by xiangshouding** [comment]
@Hancoson 正在进行中，可切换低版本 node 继续使用。

**Comment by PeakFish** [comment]
现在node版本是4.1.2了，最新的或作兼容吗？

**Comment by xiangshouding** [comment]
@PeakFish 会

**Comment by Hancoson** [comment]
可以支持雪碧图自适应吗？background-size???

**Comment by HassanChiang** [comment]
@xiangshouding  今天还是出现 csssprites does not support your node v4.1.2，还没修复吧？

**Comment by xiangshouding** [comment]
@HassanChiang 用词不当啊，应该叫 支持；正在测，不久就会发出来了。

**Comment by HassanChiang** [comment]
@xiangshouding 是的，不好意思~~~o(∩_∩)o

**Comment by dajbd** [comment]
现在2015-10-29，解决了木有呢~
报错：csssprites does not support your node v4.2.1

**Comment by 2betop** [comment]
我正在看这个问题。

**Comment by 2betop** [comment]
@dajbd 啥系统，多少位机器？

**Comment by dajbd** [comment]
windows, x64, node v4.2.1

**Comment by dajbd** [comment]
你什么系统，你没有出现此问题吗？

**Comment by 2betop** [comment]
我是 mac, 来执行下这个看是否有报错，没有的话就好办了。

```
npm install fis-spriter-csssprites@0.3.3
```

**Comment by dajbd** [comment]
更新到fis-spriter-csssprites@0.3.3，
测试仍然提示：
[WARNI] csssprites does not support your node v4.2.1, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues
 359ms

**Comment by 2betop** [comment]
试试 fis3 最新的 beta 版本

```
npm install -g fis3@beta
```

**Comment by 2betop** [comment]
@dajbd 忽略我，我没看到你回复了。

**Comment by dajbd** [comment]
@2betop 更新到fis-spriter-csssprites@0.3.3，
测试仍然提示：
[WARNI] csssprites does not support your node v4.2.1, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues
359ms

**Comment by dajbd** [comment]
@2betop 由于历史原因，暂时不能升级到fis3，见谅。但还是希望修复问题~谢谢了~你使用fis3能正常使用fis-spriter-csssprites@0.3.3？？？

**Comment by 2betop** [comment]
嗯，我这是正常的

**Comment by dajbd** [comment]
@2betop 哥们儿，帮忙解决一下fis2环境下的问题咯~良辰必有重谢~呵呵

**Comment by 2betop** [comment]
你的 issue 呢？

**Comment by dajbd** [comment]
@2betop 看到这个issue，其实是同样的报错，就没有去new issue了

**Comment by 2betop** [comment]
fis3@3.2.9
fis@1.9.36 

这两个版本都解决  windows node 4 不支持的问题了，麻烦帮忙测试一把。

**Comment by dajbd** [comment]
@2betop 测试通过。非常非常感谢，么么哒~~~

**Comment by zry656565** [comment]
@2betop 升级fis后确实好了，感谢~

**Comment by stephenzhao** [comment]
npm install fis-spriter-csssprites@0.3.3 安装后 fis2.0在mac下面 sprite 不起作用了。。虽然没提示 csssprites does not support your node v4.2.1

**Comment by 2betop** [comment]
@stephenzhao 最新是 0.3.5, 0.3.3 可能有问题。

**Comment by stephenzhao** [comment]
@2betop ok 谢谢 解决了～

**Comment by mengqing723** [comment]
还是报 ：[WARNI] csssprites does not support your node v4.4.0
fis v3.3.21
node v4.4.0
ubuntu 14.04

**Comment by xiangshouding** [comment]
@mengqing723  npm install -g fis3@beta

**Comment by mengqing723** [comment]
@xiangshouding 不报错了，但是 csssprites 好像不起作用

**Comment by mengqing723** [comment]
@xiangshouding 
呵呵，ok了，谢谢！

**Comment by quqingfei** [comment]
用这个命令把插件升级到0.3.5 ：**npm install fis-spriter-csssprites@0.3.5**就OK了！

**Comment by mixtan** [comment]
[WARNI] csssprites does not support your node v10.15.3

@xiangshouding 这个兼容问题解决了吗？

系统：win10/64位
node: v10.15.3
fis3:  v3.4.41
