### ISSUE TITLE
不支持 v0.11.9版本nodejs

### ISSUE THREAD

**Issue by yaodongwei** [fex-team/fis-spriter-csssprites#4]
[WARNI] csssprites does not support your node v0.11.9, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues

**Comment by darkmirrors** [comment]
@xiangshouding 
[WARNI] csssprites does not support your node v0.10.33, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues

**Comment by xiangshouding** [comment]
@darkmirrors 你的系统参数等？

**Comment by darkmirrors** [comment]
@xiangshouding

MAC OSX10.10 I5 256G 8G
node v0.10.33
npm v1.4.28

我clone 了这个项目在本地，打算做一些改造。但是运行报错，就是上面report那些。
我改造的目的是想加个自定导出sprite图片的路径~ 免得和css文件放在一块。

**Comment by noonhorse** [comment]
@darkmirrors 
@yaodongwei 

这个问题是因为缺少images的支持，需要 安装 [images](https://github.com/zhangyuanwei/node-images) 

```
$ npm install images -g
```

**Comment by xiangshouding** [comment]
hello all，现在已经全面支持 0.12.0 了，装最新版本的 fis 即可。

**Comment by chilebaby** [comment]
我装的node 12.2还是不行啊

**Comment by xiangshouding** [comment]
@chilebaby 啥系统，多少位的？

**Comment by sdojndx** [comment]
window8 提示
 [WARNI] csssprites does not support your node v0.12.7, report it to https://git
hub.com/xiangshouding/fis-spriter-csssprites/issues
