### ISSUE TITLE
不支持低版本浏览器hack操作

### ISSUE THREAD

**Issue by famingyuan** [fex-team/fis-spriter-csssprites#41]
比如：\*background-position: 20px 16px;
会被自动截取，只剩下了*;
本意是针对IE67 ，可现在所有浏览器都搞上了...

**Comment by xiangshouding** [comment]
确实没有处理类似的 hack 写法

不过其实你可以用一张图片，然后开始 pngquant 压缩器，基本上应该不会出现大的问题。

如若遇到这类 hack 写法 （应该也不多）可以考虑此文件不做合并处理。

**Comment by famingyuan** [comment]
恩，明白了，谢谢哈。

**Comment by SuunZhu** [comment]
有点渣，没处理好hack
