### ISSUE TITLE
bug 项目里所有图片的file.map.pkg貌似都会被设置成同一个值(以致fis3-deploy-skip-packed过滤失败)

### ISSUE THREAD

**Issue by feix760** [fex-team/fis-spriter-csssprites#43]
文件：libs/image.js
![7cb88292-aa45-46ad-9d35-53daa8c1b500](https://cloud.githubusercontent.com/assets/5415656/13773969/41560e10-ead7-11e5-83aa-54ead4eba9c7.png)

文件：index.js
![31a2ce71-bd57-4e95-bfad-548961903375](https://cloud.githubusercontent.com/assets/5415656/13773976/4a7a3cd2-ead7-11e5-9668-bf8f9add0600.png)

项目里所有的图片即使没有被合并也会被设置file.map.pkg

插件 fis3-deploy-skip-packed 通过此标志判断是否被合并

**Comment by 2betop** [comment]
这个问题已经修了，更新即可

**Comment by feix760** [comment]
good

**Comment by feix760** [comment]
刚试了一下，还有点问题

![45b74eae-581c-4d2e-bdc3-f70f99bba073](https://cloud.githubusercontent.com/assets/5415656/13800367/9ccc2fcc-eb63-11e5-89ea-acf0453931c6.png)

list里面不是file对象，可以从this.images找到它的文件对象：
![db5f8aa7-2366-4938-8b57-6d0503400d70](https://cloud.githubusercontent.com/assets/5415656/13800373/b3527080-eb63-11e5-97e5-a371f0b2afdb.png)

@2betop 求帮忙更新一下npm

**Comment by 2betop** [comment]
求 pr

**Comment by feix760** [comment]
done

**Comment by 2betop** [comment]
Thx, 已经更新到 fis 3.3.20
