### ISSUE TITLE
csssprites does not support your node v4.4.0

### ISSUE THREAD

**Issue by bingozhang** [fex-team/fis-spriter-csssprites#45]
请求 fex-team 能帮忙把node依赖调成 v4._._ 呀   你这样弄的我升级node到了4.4.0后无法使用了！！

非常感谢

**Comment by feix760** [comment]
貌似是npm fis-spriter-csssprites@0.3.9 package.json里的"images": "2.1.5"和git上的package.json "images": "2.1.11"不一致导致。麻烦 @BaiduFE 重新发一个npm，我这边也不行了

**Comment by geeyan** [comment]
之前是可以的，今天下午开始不行了

**Comment by mewtwo-chi** [comment]
跪求支持，也是这两天就不支持了，之前还可以了。我的node 4.2

**Comment by zhulin2609** [comment]
@feix760 
翔哥，到底用哪个版本的node靠谱啊？csssprites不是内置的吗？需要单独再装一次？

**Comment by zhulin2609** [comment]
@feix760 
感谢翔哥的帮助！先用0.3.8可以暂时解决这个问题！

**Comment by geeyan** [comment]
同使用 0.3.8 解决

**Comment by xiangshouding** [comment]
都是 v4.4 不好使吗？

并且你们的操作系统是啥？

**Comment by zhulin2609** [comment]
@xiangshouding 
win7。我觉得可能的原因应该就是 @feix760 说的那个

**Comment by xiangshouding** [comment]
OK，我看看！

**Comment by xiangshouding** [comment]
也不是，中间有一次重新编译了，可能引入新的问题，现在情况比较多，测试环境也是稀缺。后续等下次升级，找社区的人帮忙～
linkzhu <notifications@github.com>于2016年3月21日 周一21:57写道：

**Comment by iulo** [comment]
@xiangshouding  确实是images依赖的问题， 我直接更新了csssprite下的images版本到2.1.11就可以使用了

**Comment by 2betop** [comment]
嗯，感谢反馈，确实是不同步，已发布新版本，不过是 beta 版本，安装的时候请指定版本号或者 `fis3@beta`

**Comment by williambryan777** [comment]
[WARNI] csssprites does not support your node v7.3.0

**Comment by xiangshouding** [comment]
8.x 已支持
