### ISSUE TITLE
请问目前这个插件支持的node最高版本是？

### ISSUE THREAD

**Issue by zhulin2609** [fex-team/fis-spriter-csssprites#47]
请问目前这个插件支持的node最高版本是？

**Comment by xiangshouding** [comment]
node 4.x 理论上都支持，如果无法使用，尝试升级最新版本的 fis。如再有问题，请再沟通~

**Comment by zhulin2609** [comment]
更新了最新版的node 4.4，提示如下：
`[WARNI] csssprites does not support your node v4.4.0, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues`

**Comment by will-** [comment]
btw, 这个report的地址也该更新了

**Comment by MangueWoo** [comment]
[WARNI] csssprites does not support your node v4.4.2, report it to https://github.com/xiangshouding/fis-spriter-cssspri
tes/issues

**Comment by xiangshouding** [comment]
https://github.com/fex-team/fis3/releases/tag/3.3.23
