### ISSUE TITLE
啥时可支持node v5.8.0？

### ISSUE THREAD

**Issue by fishinwater** [fex-team/fis-spriter-csssprites#48]
[WARNI] csssprites does not support your node v5.8.0, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues

report 指向的路径404

**Comment by xiangshouding** [comment]
5.x  改了 API 接口啊，改了接口弄起来特别的花时间。我正在调研直接用纯 js 实现，等有结果再回复你吧。

**Comment by fishinwater** [comment]
多谢多谢。
