### ISSUE TITLE
does not support your node v4.4.7

### ISSUE THREAD

**Issue by jin925** [fex-team/fis-spriter-csssprites#60]
csssprites does not support your node v4.4.7

**Comment by xiangshouding** [comment]
这个就尴尬了，重装试试，更新最新的 node 试试。

**Comment by jin925** [comment]
已经搞到6.5版本，问题依旧。
![image](https://cloud.githubusercontent.com/assets/5148826/18460273/aa594684-79a2-11e6-8c59-0646bc935d45.png)

**Comment by hanyiTim** [comment]
v4.4.4   64   也是同样的问题~~~~

**Comment by xiangshouding** [comment]
以前做了安装时加载对应的插件这样一个事情，如果你升级了 node 需要重新安装 fis。如果可以重装后再试试。实在不行，请报上你的操作系统相关的详细信息。

**Comment by hanyiTim** [comment]
按照楼上说的 已经可以了，谢谢
