### ISSUE TITLE
csssprites does not support your node v6.9.1

### ISSUE THREAD

**Issue by feitiange** [fex-team/fis-spriter-csssprites#61]
node 6.9.1
fis3 3.4.13
fis-spriter-csssprites 0.3.11
Linux 2.6.32-504.el6.x86_64

**Comment by maxming2333** [comment]
有报错截图么

**Comment by maxming2333** [comment]
或者其他信息？

**Comment by feitiange** [comment]
.
 [33m[WARNI][39m Onymous module `jquery` is not allowed here in `/static/js/lib/require_jquery.js`, but it will be erased anyway.
..........................[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m[90m.[39m......
 [33m[WARNI][39m csssprites does not support your node v6.9.1, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues
[32m[1m 2.27s[22m[39m
+ mv dist output

**Comment by feitiange** [comment]
![image](https://cloud.githubusercontent.com/assets/7125157/20699383/0cf3748c-b642-11e6-9323-1d29957c060d.png)

**Comment by maxming2333** [comment]
@2betop [master/index.js#L15](https://github.com/fex-team/fis-spriter-csssprites/blob/master/index.js#L15)

**Comment by feitiange** [comment]
![image](https://cloud.githubusercontent.com/assets/7125157/20702266/10a18b04-b652-11e6-9faa-51903d727d7b.png)

**Comment by lengjing** [comment]
node7.0也遇到了相同的问题

**Comment by xiangshouding** [comment]
@feitiange 找一台有 glibc_2.14 的 copy 一份就可以。

**Comment by xiangshouding** [comment]
@lengjing 

node 7 的应该还没有编译

**Comment by Dengjiansheng** [comment]
[安装glibc_2.14](http://www.laozuo.org/9687.html)
我是按照这个教程安装了`glibc_2.14`的
之后就可以用`csssprites`了

**Comment by xiangshouding** [comment]
8.x 已支持
