### ISSUE TITLE
csssprites does not support your node v6.9.2

### ISSUE THREAD

**Issue by jiangyang118** [fex-team/fis-spriter-csssprites#63]
你好，我在Windows上安装fis3，运行fis提供的demo-simple，均没有问题。接着在linux环境上安装fis3,后，运行demo-simple报如下错误：

>  [WARNI] csssprites does not support your node v6.9.2, report it to https://github.com/xiangshouding/fis-spriter-csssprites/issues
linux版本是64位的centos6.3
请问如何解决，谢谢

**Comment by a526672351** [comment]
我的也是这个警告，linux环境下面不行

**Comment by xiangshouding** [comment]
忽略，暂时只会影响图片合并功能，如果是百度内部的，请联系 FIS 小组解决。如果是外面公司的，提供你们所有操作系统信息，以及 fis3 的版本。

**Comment by a526672351** [comment]
系统版本是CentOS6.5,
fis3版本3.4.34，
编译的时候会报两个错误警告如图：
[WARNI] node-pngcrush does not support your node v6.9.4, report it to 
[WARNI] csssprites does not support your node v6.9.4, report it to

**Comment by a526672351** [comment]
在window环境，node v6.10.0 版本都没有问题

**Comment by xiangshouding** [comment]
done

**Comment by a526672351** [comment]
@xiangshouding fis-spriter-csssprites 是fis3内置的插件，要重新升级fis3版本就可以解决了吗？
