### ISSUE TITLE
同一CSS文件中的四个图片,打包成了三个.想要只打包成一个需要什么操作吗?

### ISSUE THREAD

**Issue by NNorLand** [fex-team/fis-spriter-csssprites#64]
同一个CSS文件中,四张图片,编译之后,变成了三个,,,能否指导下,打包成一个?
<img width="200" alt="qq20170109-180034 2x" src="https://cloud.githubusercontent.com/assets/17919003/21762818/b82d8d4c-d695-11e6-996b-7df296789386.png">

**Comment by NNorLand** [comment]
测试,需要background-size大小相同才会合并

**Comment by xiangshouding** [comment]
这个问题后续跟进一下。
