### ISSUE TITLE
 csssprites does not support your node v7.10.0

### ISSUE THREAD

**Issue by blithe6317** [fex-team/fis-spriter-csssprites#69]
node-pngcrush does not support your node v7.10.0, report it to https://github.com/xiangshouding/node-pngcrush/issues
无法压缩图片

**Comment by blithe6317** [comment]
win10 64

**Comment by xiangshouding** [comment]
确实不支持，正在努力支持 8.x 中。

**Comment by xiangshouding** [comment]
已支持 8.x
